---
output: 
  html_document:
   theme: null
   mathjax: null
   highlight: null
   css: margin_css.css
---

```{r setup, include=F}

require(dplyr)
require(tidyr)
require(rgdal)
require(rgeos)
require(sp)
require(leaflet)

knitr::opts_chunk$set(echo = F,message = F,warning = F)


#bounds<-readOGR(dsn = "C:/Users/TCLARKE1/OneDrive - Department for #Education/Documents/GIS","Westminster_Parliamentary_Constituencies_December_2018_GB_BFE_V2")

#bounds<-bounds[grepl("^E",bounds@data$pcon18cd),]

#bounds<-rmapshaper::ms_simplify(bounds,keep=0.005)

#bounds<-spTransform(bounds,CRS("+init=epsg:4326"))

pcPop<-readr::read_csv("//Lonnetapp01/NDPB OCC Research and Data Analysis Restricted/APMS/Toxic trio LA level backup 18112019/Toxic trio LA level/Parliamentary constituency/pCon0-17.csv")

bounds<-readRDS("//Lonnetapp01/NDPB OCC Research and Data Analysis Restricted/APMS/Toxic trio LA level backup 18112019/Toxic trio LA level/Parliamentary constituency/bounds_simple.rds")

pcEst<-readr::read_csv("//Lonnetapp01/NDPB OCC Research and Data Analysis Restricted/APMS/Toxic trio LA level backup 18112019/Toxic trio LA level/Parliamentary constituency/pcEst.csv")
resConf_rose_use <-readr::read_csv("//Lonnetapp01/NDPB OCC Research and Data Analysis Restricted/APMS/Toxic trio LA level backup 18112019/Toxic trio LA level/Parliamentary constituency/pcEst_rose.csv")

outLab<-readxl::read_excel("//Lonnetapp01/NDPB OCC Research and Data Analysis Restricted/APMS/Toxic trio LA level backup 18112019/Toxic trio LA level/coding sheets_web.xlsx","outcomes")

popSize<-readr::read_csv("//Lonnetapp01/NDPB OCC Research and Data Analysis Restricted/APMS/Toxic trio LA level backup 18112019/Toxic trio LA level/Parliamentary constituency/popSize.csv")

depRank<-readr::read_csv("//Lonnetapp01/NDPB OCC Research and Data Analysis Restricted/APMS/Toxic trio LA level backup 18112019/Toxic trio LA level/Parliamentary constituency/depRank.csv")

depDec<-readr::read_csv("//Lonnetapp01/NDPB OCC Research and Data Analysis Restricted/APMS/Toxic trio LA level backup 18112019/Toxic trio LA level/Parliamentary constituency/depDec.csv")

mpList<-readr::read_csv("//Lonnetapp01/NDPB OCC Research and Data Analysis Restricted/APMS/Toxic trio LA level backup 18112019/Toxic trio LA level/Parliamentary constituency/mpList_out.csv")


pc_use<-pcEst %>% bind_rows() %>%
  select(pc,outcome,fRate=popRate,fLower,fUpper,estRate=fRate) %>% 
  bind_rows(resConf_rose_use %>%
       left_join(outLab %>% select(outcome,popRate)) %>%
      select(pc,outcome,fRate=popRate,fLower,fUpper,estRate=fRate)) %>%
  mutate(est=fRate) %>%
  left_join(popSize %>% select(-pop),by=c("pc"="pc")) %>%
  select(-fRate)

pc_use<-pc_use %>%
  left_join(pcPop %>% select(PCON11NM,pop=pop017)) %>%
  mutate(popRate=round(est*pop,0),
   modRate_low=round(fLower*pop,0),
    modRate_high=round(fUpper*pop,0),
    modRate_mid=round(estRate*pop,0)) %>% select(-pop)



require(cdata)

cT<-data.frame(outcome=unique(pc_use$outcome),estRate=paste0(unique(pc_use$outcome),"_model"),
  est=paste0(unique(pc_use$outcome),"_pop"),popRate=paste0(unique(pc_use$outcome),"_popN"),
  modRate_low=paste0(unique(pc_use$outcome),"_modLow"),
  modRate_high=paste0(unique(pc_use$outcome),"_modHigh"),
  modRate_mid=paste0(unique(pc_use$outcome),"_modMid"),stringsAsFactors = F)

pc_use<-blocks_to_rowrecs(pc_use,keyColumns = "pc",controlTable = cT,columnsToCopy = c("PCON11CD","PCON11NM","LAnum"))



laBounds<-readRDS("//Lonnetapp01/NDPB OCC Research and Data Analysis Restricted/APMS/Toxic trio LA level backup 18112019/Toxic trio LA level/Parliamentary constituency/laBounds_simple.rds")

laBounds<-spTransform(laBounds,CRS("+init=epsg:4326"))

laEst<-readr::read_csv("//Lonnetapp01/NDPB OCC Research and Data Analysis Restricted/APMS/Toxic trio LA level backup 18112019/Toxic trio LA level/Parliamentary constituency/laEstimates.csv") %>% filter(!grepl("synthetic",outcome))

laEst_rose<-readr::read_csv("//Lonnetapp01/NDPB OCC Research and Data Analysis Restricted/APMS/Toxic trio LA level backup 18112019/Toxic trio LA level/Parliamentary constituency/laEstimates_rose.csv") 



laEst<-laEst %>% #filter(!outcome %in% c("alcordrugsep","submisuse")) %>%
  group_by(outcome) %>%
  mutate(m=mean(mid)) %>%
  ungroup() %>%
  left_join(outLab %>% select(outcome,popRate,labOutcome) %>% mutate(popRate=popRate/100)) %>%
  mutate(popMult=mid/m) %>%
  mutate(confU=upper-mid,confL=mid-lower) %>%
  mutate(fRate=popRate*popMult) %>%
  mutate(fUpper=fRate+confU,fLower=ifelse(fRate-confL<0,0,fRate-confL))

laEst_rose<-laEst_rose %>% ungroup() %>%
  mutate(fRate=scales::rescale(mid,c(min(laEst$fRate[laEst$outcome=="toxictrionarrow"]),max(laEst$fRate[laEst$outcome=="toxictrionarrow"])))) %>%
  mutate(outcome="toxictrionarrow_synthetic")

la_use<-laEst %>%
  select(la=LA_152,cd=LA152_Code,fRate,outcome) %>% 
  bind_rows(laEst_rose %>% select(la=LA_152,cd=LA152_Code,fRate,outcome)) %>%
  mutate(est=fRate*100) %>%
  select(-fRate) %>%
  spread(key=outcome,value=est)

laPop<-readr::read_csv("//Lonnetapp01/NDPB OCC Research and Data Analysis Restricted/Gangs Review data/Analysis/Gangs/hotspots_summit/onsPop.csv") %>%
  filter(age<18) %>%
  group_by(area) %>%
  summarise(pop=sum(population_2017))

```

```{r, echo=F,message=F,warning=F,out.width="100%"}

require(dplyr)
require(tidyr)
require(leaflet)


for(i in names(la_use)[3:length(names(la_use))]){
nVar<-rlang::sym(paste0(i,"_fill"))
var<-rlang::sym(i) 

la_use <- la_use %>% ungroup() %>%
  mutate(!!nVar:=scales::rescale((!!var),c(0,1))) }

la_use<-la_use %>%
  left_join(laPop,by=c("cd"="area"))

c<-sp::merge(laBounds,as.data.frame(la_use),by.x="ctyua16cd",by.y="cd",all.x=T,all.y=T)
pal <- colorNumeric("viridis", domain = c(0,1))



labels <- lapply(names(la_use)[!grepl("_fill|^la|^cd",names(la_use))],function(x){
  paste0(
  "<strong>",c$la,"</strong><br/>Projected % of children in households where an ",gsub(" [(].*[)]","",tolower(outLab$labOutcome[outLab$outcome==x]))," : ",round(c@data[,x],2),
  "%<br/>Projected number of 0-17 yr olds affected: ",round(c@data[,x]/100*c@data$pop,-1)) %>% lapply(htmltools::HTML)
})

names(labels)<-names(la_use)[!grepl("_fill|^la|^cd",names(la_use))]


leaflet() %>%
  addProviderTiles(providers$CartoDB) %>%
  addPolygons(data=c,color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.7,fillColor = ~pal(`alcordrugdep_fill`),
    popupOptions = highlightOptions(bringToFront = T,weight=4),group="Alcohol/substance misuse",popup =labels[["alcordrugdep"]]) %>%

  addPolygons(data=c,color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.7,fillColor = ~pal(`dvavictimyear_fill`),
    popupOptions = highlightOptions(bringToFront = T,weight=4),group="Domestic abuse",popup =labels[["dvavictimyear"]]) %>%
  
  addPolygons(data=c,color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.7,fillColor = ~pal(`severemhprob_fill`),
    popupOptions = highlightOptions(bringToFront = T,weight=4),group="Mental health problems",popup =labels[["severemhprob"]]) %>%
  
  addPolygons(data=c,color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.7,fillColor = ~pal(`oneplusharmsnarrow_fill`),
    popupOptions = highlightOptions(bringToFront = T,weight=4),group="Any of the above risks",popup =labels[["oneplusharmsnarrow"]]) %>%
  
  addPolygons(data=c,color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.7,fillColor = ~pal(`twoplusharmsnarrow_fill`),
    popupOptions = highlightOptions(bringToFront = T,weight=4),group="2 or more of the above risks",popup =labels[["twoplusharmsnarrow"]]) %>%
  
    addPolygons(data=c,color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.7,fillColor = ~pal(`toxictrionarrow_synthetic_fill`),
    popupOptions = highlightOptions(bringToFront = T,weight=4),group="All 3 of the above risks",popup =labels[["toxictrionarrow_synthetic"]]) %>%
  
  addLayersControl(
   baseGroups = c("Alcohol/substance misuse", "Domestic abuse","Mental health problems",
     "Any of the above risks","2 or more of the above risks","All 3 of the above risks"),
    options = layersControlOptions(collapsed = FALSE)) %>%
   addLegend("topleft", pal = pal, values = seq(0,1),bins=5,
     labFormat = function(type, cuts, p) { 
       n = length(cuts) 
       cuts[n] = "Highest rate" 
       for (i in 2:(n-1)){cuts[i] = " "} 
       cuts[1] = "Lowest rate" 
       paste0(cuts[-n], cuts[-1])},
    title = "Projected rate of children<br/>affected in<br/>local authority",
     na.label = "Missing/excluded",
    opacity = 0.7
  ) 

```

```{r, results='asis',echo=F,warning=F}
minVals<-sapply(la_use[,c("alcordrugdep","dvavictimyear","severemhprob","oneplusharmsnarrow",
   "twoplusharmsnarrow","toxictrionarrow_synthetic")],function(x,y){
     
     paste0(round(min(x),4)*100,"%")
     
   }) 

maxVals<-sapply(la_use[,c("alcordrugdep","dvavictimyear","severemhprob","oneplusharmsnarrow",
   "twoplusharmsnarrow","toxictrionarrow_synthetic")],function(x,y){
     
     paste0(round(max(x),4)*100,"%")
     
   }) 


minVals<-jsonlite::toJSON(minVals,"values")

maxVals<-jsonlite::toJSON(maxVals,"values")

cat(paste0('<script>
  
  window.addEventListener("load", function () {
    var eles = document.getElementsByClassName("leaflet-control-layers-base");
    
    eles[0].insertAdjacentHTML("afterbegin","<span style=',"'","margin-bottom:3px;font-weight:bold","'",'>Select measure to view:</span>")

  var maxArr = ',maxVals,';

  var minArr = ',minVals,';

  var legendEntries = document.getElementsByClassName("leaflet-control-layers-selector")

  for (var i=0; i < legendEntries.length; i++){

  legendEntries[i].setAttribute("minval_map",minArr[i])

  legendEntries[i].setAttribute("maxval_map",maxArr[i])

  }

var legend_1 = document.getElementsByClassName("info legend leaflet-control")[0]

  var legEntries_1 = legend_1.getElementsByTagName("text")

  legEntries_1[0].innerHTML = minArr[0]

  legEntries_1[0].setAttribute("dx",60)

  legEntries_1[legEntries_1.length - 1].innerHTML = maxArr[0]

  legEntries_1[legEntries_1.length - 1].setAttribute("dx",60)


f3 = function(){

  var minVal_var = this.getAttribute("minval_map")

  var maxVal_var = this.getAttribute("maxval_map")

  var legend = document.getElementsByClassName("info legend leaflet-control")[0]

  var legEntries = legend.getElementsByTagName("text")

  legEntries[0].innerHTML = minVal_var

  legEntries[0].setAttribute("dx",60)

  legEntries[legEntries.length - 1].innerHTML = maxVal_var

  legEntries[legEntries.length - 1].setAttribute("dx",60)

  }

  for (var i=0; i < legendEntries.length; i++){

  legendEntries[i].addEventListener("click",f3)

  }
    
})

  
  

  </script>'
  ))
```
